//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityUygulamaProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Kullanici
    {
        public short KullaniciID { get; set; }
        public string KullaniciAd { get; set; }
        public string KullaniciSifre { get; set; }
    }
}
